Install Ubuntu dependencies needed to run GUI tests
The GitHub Action runner reports:
ImportError: libEGL.so.1: cannot open shared object file: No such file
or directory

Fix this by including the installation of the libegl1-mesa-dev package

Tests:
 - Verify after push