Fix dev mode being unable to run "oic"
Turns out the way that the console_scripts entry point for the
"oic" wrapper was incorrectly specified. Followed this:
https://stackoverflow.com/a/27785121/6353
which stops this sort of error which used to appear when
installing in development mode (i.e. "pip install -e .")

$ oic
Traceback (most recent call last):
  File "/home/dave/.local/bin/oic", line 33, in <module>
    sys.exit(load_entry_point('openinverter-can-tool', 'console_scripts', 'oic')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.local/bin/oic", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 204, in load
    return functools.reduce(getattr, attrs, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'openinverter_can_tool' has no attribute 'cli'

Tests:
 - Run "oic" in dev mode on F37
 - Run tox to test across python versions
 - Run "oic" in a virtual environment